api/urls.py
from django.urls import path, include
from rest_framework import routers, serializers, viewsets

from mod.models import Mod
from .views import latest, modSearch, modDownload


router = routers.DefaultRouter()

router.register(r'mod/modDownload', modDownload)
router.register(r'mod/latest', latest)
router.register(r'mod', modSearch)


urlpatterns = [
    path('', include(router.urls)),
    path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

mod/urls.py
from django.urls import path, include

from . import views

from .views import SearchResultsView

app_name = 'mod'

urlpatterns = [
    path('submit/', views.submit, name='submit'),
    path('botlatest/', views.latest, name='latest'),
    path('<int:pk>/', views.modPage, name='modPage'),
    path('<int:pk>/edit', views.modEdit, name='modEdit'),
    path('<int:pk>/delete', views.modDelete, name='modDelete'),
    path('search/', SearchResultsView.as_view(), name='modSearch'),
    path('filter/', views.modTagFilter, name='modTagFilter'),
    path('likes/', include('likes.urls')),
    path('<int:pk>/reviewupvote/', views.reviewUpVote, name='reviewUpvote'),
    path('<int:pk>/reviewremovevote/', views.reviewRemoveVote, name='reviewRemoveVote'),
    path('<int:pk>/reviewdownvote/', views.reviewDownVote, name='reviewDownvote'),
    path('<int:pk>/reviewdelete/', views.reviewDelete, name='reviewDelete'),
    path('<int:pk>/reviewedit/', views.reviewEdit, name='reviewEdit'),
    path('<int:pk>/rating/', views.rating, name='rating'),
    path('<int:pk>/ratingdelete/', views.ratingDelete, name='ratingDelete'),
    path('<int:pk>/news/', views.news, name='news'),
    path('<int:pk>/notifications/', views.notification, name='notification'),
    path('awards2018/', views.awards2018, name='awards2018'),
    path('awards2019/', views.awards2019, name='awards2019'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

from . import views

urlpatterns = [
    #path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('pages.urls')),
    path('mod/', include('mod.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path(r'^progressbarupload/', include('progressbarupload.urls')),
    path('avatar/', include('avatar.urls')),

]

handler404 = views.handler404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

from . import views

urlpatterns = [
    #path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('pages.urls')),
    #path('mod/', include('mod.urls')),
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    #path('accounts/', include('accounts.urls')),
    #path('avatar/', include('avatar.urls')),
    path('api/', include('api.urls')),
]

handler404 = views.handler404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mod/forms.py
from django import forms
from django.core.validators import URLValidator, MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
from.models import Mod, ReviewRating, Rating, News, Vote, ModEdit
from embed_video.fields import EmbedVideoFormField

from tempus_dominus.widgets import DatePicker

#class SubmitForm(forms.Form):
#    modName = forms.CharField(label='Mod name', max_length=100)
#    modDescription = forms.CharField(label='Mod description', max_length=10000)
#    modWebsite = forms.CharField(label='Mod website', max_length=100, validators=[URLValidator])
#    modTag = forms.CharField(label='Mod tags', max_length=1000)
#    modCreditPerms = forms.CharField(label='Mod credits and permissions', max_length=1000)
#    modDonations = forms.CharField(label='Mod donations', max_length=1000)
#    modSocial = forms.CharField(label='Mod Social', max_length=100)

#    def clean_modTag(self):
#        data = self.cleaned_data['modTag']
#        if '.' in data:
#            raise ValidationError(_('Invalid tags - tags cannot have full stops.'))
#        return data


class SubmitForm(forms.ModelForm):
    modDescription = forms.CharField(widget=forms.Textarea, max_length=10000)
    modShortDescription = forms.CharField(widget=forms.Textarea, max_length=250)
    modContact = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Please enter any information that we can use to contact you if we find a problem with your mod submission. This is not publicly available, and can only be seen by the moderators.'}), max_length=1000)
    modDate = forms.DateTimeField(widget=DatePicker(), initial='2020-01-01')

    modUploadURL = forms.URLField(max_length=200, widget=forms.TextInput, help_text="Only Google Drive and MEGA are currently supported.")

    #modPreviewVideo = EmbedVideoFormField(help_text="Only YouTube and Vimeo links are currently supported.")

    class Meta:
        model = Mod
        fields = ('modID', 'modName', 'modStatus', 'modDescription', 'modShortDescription', 'tags',
                  'modUploadURL', 'modPlayTimeHours', 'modPlayTimeMinutes', 'modPreviewVideo', 'modPreviewImage1',
                  'modPreviewImage2', 'modPreviewImage3', 'modPreviewImage4', 'modPreviewImage5', 'modBackground',
                  'modBackgroundTiledStretch', 'modAvatar', 'modDate', 'modContact')


class EditForm(forms.ModelForm):
    modDescription = forms.CharField(widget=forms.Textarea, max_length=10000)
    modShortDescription = forms.CharField(widget=forms.Textarea, max_length=250)
    modContact = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Please enter any information that we can use to contact you if we find a problem with your mod submission. This is not publicly available, and can only be seen by the moderators.'}), max_length=1000)
    modDate = forms.DateTimeField(widget=DatePicker(), initial='2020-01-01')

    modUploadURL = forms.URLField(max_length=200, widget=forms.TextInput, help_text="Only Google Drive and MEGA are currently supported.")

    #modPreviewVideo = EmbedVideoFormField(help_text="Only YouTube and Vimeo links are currently supported.")

    class Meta:
        model = ModEdit
        fields = ('modEditID', 'modName', 'modStatus', 'modDescription', 'modShortDescription', 'tags',
                  'modUploadURL', 'modPlayTimeHours', 'modPlayTimeMinutes', 'modPreviewVideo', 'modPreviewImage1',
                  'modPreviewImage2', 'modPreviewImage3', 'modPreviewImage4', 'modPreviewImage5', 'modBackground',
                  'modBackgroundTiledStretch', 'modAvatar', 'modDate', 'modContact')


class ReviewForm(forms.ModelForm):
    reviewComment = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = ReviewRating
        fields = ('reviewid', 'reviewComment')


class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields = ('voteID', 'voteReviewID', 'voteAuthor', 'voteValue')


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ('ratingID', 'ratingModID', 'ratingAuthorID', 'ratingValue')


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ('newsID', 'newsModID', 'newsText')

mod/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseForbidden
from django.contrib.auth.models import User, Group
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.contrib.postgres.search import SearchVector
from django.views.generic.list import ListView
from django.views.generic import TemplateView, FormView
from django.db.models import F, Q, Count, Sum, Avg
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.core import serializers, mail
from django.core.mail import send_mail
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.http import Http404

import json, pdb, math, datetime

from django_filters.views import FilterView
from taggit.models import Tag
from PIL import Image

from .forms import SubmitForm, ReviewForm, NewsForm, EditForm
from .models import Mod, ReviewRating, Rating, News, NewsNotifications, Vote, ModEdit, EditReviewRating  # , ModFilter
from .scripts import moveMod
from .operations.mail import notificationsSendMail
from .scripts import removeEdit

from accounts.models import User


# Create your views here.

def visitor_ip_address(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')

    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def index(request):
    return render(request, 'mod/index.html')


@login_required
def submit(request):
    if request.method == 'POST':
        form = SubmitForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.modAuthor = request.user
            #post.modDate = timezone.now()
            post.modUpdate = timezone.now()
            post.modShow = False
            post.modIP = visitor_ip_address(request)
            post.save()
            post.save()
            form.save_m2m()
            post.tags.add("All")
            for x in post.tags.names():
                print(x)
                if str(x) == "nsfw":
                    post.modNSFW = True
            post.modShow = False
            post.save()
            user = User.objects.get(id=request.user.id)
            user.totalMods = user.totalMods + 1
            group = Group.objects.get(name="Mod Creators")
            group.user_set.add(request.user)
            user.save()
            return redirect('mod:modPage', pk=post.pk)
    else:
        form = SubmitForm()
    return render(request, 'mod/submitMod.html', {'form': form})


def modPage(request, pk):
    post = get_object_or_404(Mod, pk=pk)
    if not post.modIP:
        return render(request, 'mod/modPage.html', {'post': post})
    else:
        pass
    review = ReviewRating.objects.filter(reviewModID=post.modID)
    vote = Vote.objects.all()
    if request.user.is_authenticated:
        try:
            rating = Rating.objects.get(ratingAuthorID=request.user, ratingModID=post.modID)
        except ObjectDoesNotExist:
            rating = None
    else:
        rating = None

    questions = ReviewRating.objects.annotate(number_of_votes=Sum('reviewVotes'))

    post.tags = Tag.objects.all()

    news = News.objects.filter(newsModID=pk)

    if request.user.is_authenticated:
        try:
            newsnotifications = NewsNotifications.objects.get(newsNotificationsUserID=request.user.id, newsNotificationsModID=pk)
        except ObjectDoesNotExist:
            newsnotifications = None
    else:
        newsnotifications = None

    emails = get_user_model().objects.all()  # czech it

    if request.method == 'POST':
        commentForm = ReviewForm(request.POST)
        if commentForm.is_valid():
            postReview = commentForm.save(commit=False)
            postReview.reviewModID = Mod.objects.get(modID=post.modID)
            # postReview.reviewAuthor = request.user
            postReview.reviewAuthorID = request.user
            postReview.reviewApproved = False
            postReview.save()
            user = User.objects.get(id=request.user.id)
            user.totalComments = user.totalComments + 1
            user.save()
            return redirect('mod:modPage', pk=post.pk)
    else:
        commentForm = ReviewForm()
    return render(request, 'mod/modPage.html', {'post': post, 'commentForm': commentForm, 'review': review,
                                                'questions': questions, 'rating': rating, 'news': news,
                                                'newsnotifications': newsnotifications, 'emails': emails, 'vote': vote})


@login_required
def reviewUpVote(request, pk):
    if request.method == 'POST':
        request_getdata = request.POST.get('id')
        voteReviewID = ReviewRating.objects.get(reviewid__exact=request_getdata)
        response_data = {}
        post = Vote(voteReviewID=voteReviewID, voteAuthor=request.user, voteValue=1)
        post.save()
        reviewrating = ReviewRating.objects.get(reviewid=voteReviewID)
        allVotes = Vote.objects.filter(voteReviewID__exact=request_getdata).count()
        reviewrating.reviewVotes = allVotes
        reviewrating.save()
        group = Group.objects.get(name="Well respected")
        if allVotes >= 10:
            group.user_set.add(
                reviewrating.reviewAuthorID)  # User.objects.get(id=reviewrating.reviewAuthorID))#User.objects.get(username=reviewrating.reviewAuthor).id))
        else:
            group.user_set.remove(
                reviewrating.reviewAuthorID)  # User.objects.get(id=reviewrating.reviewAuthorID))#User.objects.get(username=reviewrating.reviewAuthor).id))
        response_data['result'] = "Successfully upvoted review " + request_getdata

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )


@login_required
def reviewRemoveVote(request, pk):
    if request.method == 'POST':
        response_data = {}
        request_getdata = request.POST.get('id')
        voteReviewID = ReviewRating.objects.get(reviewid__exact=request_getdata)
        reviewrating = ReviewRating.objects.get(reviewid=voteReviewID)
        Vote.objects.get(voteReviewID__exact=voteReviewID, voteAuthor=request.user).delete()
        allVotes = Vote.objects.filter(voteReviewID__exact=request_getdata).count()
        reviewrating.reviewVotes = allVotes
        reviewrating.save()
        group = Group.objects.get(name="Well respected")
        if allVotes >= 10:
            group.user_set.add(
                reviewrating.reviewAuthorID)  # User.objects.get(id=reviewrating.reviewAuthorID))#User.objects.get(username=reviewrating.reviewAuthor).id))
        else:
            group.user_set.remove(
                reviewrating.reviewAuthorID)  # User.objects.get(id=reviewrating.reviewAuthorID))#User.objects.get(username=reviewrating.reviewAuthor).id))
        response_data['result'] = "Successfully removed vote from review " + request_getdata

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )


@login_required
def reviewDownVote(request, pk):
    if request.method == 'POST':
        request_getdata = request.POST.get('id')
        voteReviewID = ReviewRating.objects.get(reviewid__exact=request_getdata)
        response_data = {}
        post = Vote(voteReviewID=voteReviewID, voteAuthor=request.user, voteValue=-1)
        post.save()
        reviewrating = ReviewRating.objects.get(reviewid=voteReviewID)
        votesAgg = Vote.objects.filter(voteReviewID__exact=request_getdata).aggregate(totalVoted=Sum('voteValue'))[
            'totalVoted']
        # allVotes = Vote.objects.aggregate(totalVoted=Sum(votesAgg))
        reviewrating.reviewVotes = votesAgg
        reviewrating.save()
        group = Group.objects.get(name="Well respected")
        if votesAgg >= 10:
            group.user_set.add(
                reviewrating.reviewAuthorID)  # User.objects.get(id=reviewrating.reviewAuthorID))#User.objects.get(username=reviewrating.reviewAuthor).id))
        else:
            group.user_set.remove(
                reviewrating.reviewAuthorID)  # User.objects.get(id=reviewrating.reviewAuthorID))#User.objects.get(username=reviewrating.reviewAuthor).id))
        response_data['result'] = "Successfully downvoted review " + request_getdata

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )


@login_required
def reviewDelete(request, pk):
    if request.method == 'POST':
        request_getdata = request.POST.get('id')
        ReviewRating.objects.get(reviewid__exact=request_getdata).delete()
        try:
            EditReviewRating.objects.get(reviewid__exact=request_getdata).delete()
        except ObjectDoesNotExist:
            pass
        response_data = {}
        response_data['result'] = "Successfully deleted review " + request_getdata
        user = User.objects.get(id=request.user.id)
        user.totalComments = user.totalComments - 1
        user.save()

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:

mod/templates/mod/modEdit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="pagewrap">
    <title>Edit {{ post.modName }}</title>
    <link rel="stylesheet" href="{% static 'css/selectize.django.css' %}">
    <link rel="stylesheet" href="{% static 'css/modSubmitEdit.css' %}">
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script type="text/javascript" src="{% static 'js/selectize.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/submit.js' %}"></script>
    {{ form.media }}
    {% if post.modAuthor == user %}
    {% if post.modShow %}
    {% if alreadyEdited %}
    <div class="editErrorList">
        <p>You have already submitted an edit for this mod. If you submit another edit, all of the changes that you made in your previous edit will be lost! Make sure you apply the changes again below, or wait until a moderator has approved the edit.</p>
    </div>
    {% endif %}
    {% if form.errors %}
    <div class="editErrorList">
        {% for field in form %}
        {% for error in field.errors %}
        <p>{{ field.label }} : {{ field.errors }}</p>
        {% endfor %}
        {% endfor %}
    </div>
    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        <!--<strong>{{ error|escape }}</strong> <h1> BLOCK THIS </h1>-->
    </div>
    {% endfor %}
    {% endif %}
    <p>If you need help, please read the <a href="{% url 'submittingMods' %}#editmod" target="_blank">edit guide</a>.</p>
    <p><b>Your mod will need to be approved manually by moderators, after you edit your mod. This could take some time.</b></p>
    <form id="myForm" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="rowLeft">
                <p>Mod Name: </p>
            </div>
            <div class="rowRight">
                {{ form.modName }}
            </div>
        </div>
        <div class="row">
            <div class="rowLeft">
                <p>Mod Status: </p>
            </div>
            <div class="rowRight">
                {{ form.modStatus }}
            </div>
        </div>
        <div class="row">
            <div class="rowLeft">
                <p>Mod Description: </p>
            </div>
            <div class="rowRight">
                {{ form.modDescription }}
            </div>
        </div>
        <div class="row">
            <div class="rowLeft">
                <p>Mod Short Description: </p>
            </div>
            <div class="rowRight">
                {{ form.modShortDescription }}
            </div>
        </div>
        <div class="row">
            <div class="rowLeft">
                <p>Tags: </p>
            </div>
            <div class="rowRight">
                {{ form.tags }}
            </div>
        </div>
        <div class="row">
            <div class="rowLeft">
                <p>Mod Upload URL: </p>
            </div>
            <div class="rowRight">
                {{ form.modUploadURL }}
            </div>
        </div>
        <div class="row">
            <div class="rowLeft">
                <p>Mod Date: </p>
            </div>
            <div class="rowRight" style="position: relative">
                {{ form.modDate }}
            </div>
        </div>
        <div class="row">
            <div class="rowLeft">
                <p>Average Play Time: </p>
            </div>
            <div class="rowRight">
                <div class="rowPlayTime"><p>{{ form.modPlayTimeHours }}h {{ form.modPlayTimeMinutes }}m</p></div>
            </div>
        </div>
        <div class="row">
            <div class="rowLeft">
                <p>Trailer Video: </p><label title="{{ form.modPreviewVideo.help_text }}" for="{{ form.modPreviewVideo.1 }}"> ! </label>
            </div>
            <div class="rowRight">
                {{ form.modPreviewVideo }}
            </div>
        </div>
        <div class="row">
            <div class="rowLeft">
                <p>Preview Images: </p>
            </div>
            <div class="rowRight">
                <div class="rowPreviewImages">
                    <div class="previewImage">
                        {% if post.modPreviewImage1 %}
                        <div class="hidden">{{ form.modPreviewImage1 }}</div>
                        <img id="previewImage1" onmouseover="previewMouseOver(1)" onmouseleave="previewMouseLeave(1)" src={{ post.modPreviewImage1.url }} alt="Preview Image 1">
                        <p>Remove image:</p>
                        <input style="width: 20px; display: inline; margin-bottom: 10px" class="modPreviewImageCheckbox" id="modPreviewImage1-clear_id" type="checkbox" name="modPreviewImage1-clear">
                        {% endif %}
                        <input class="modPreviewImageInput" id="id_modPreviewImage1" type="file" name="modPreviewImage1" accept="image/*">
                        <input style="background-color: #8acaff; width: 100%" type="button" id="showNextButton1" onclick="showNext(2, 1)" value="Upload/change more preview images">
                    </div>
                    <div id="hiddenNextImage2">
                        <div class="previewImage">
                            {% if post.modPreviewImage2 %}
                            <div class="hidden">{{ form.modPreviewImage2 }}</div>
                            <img id="previewImage2" onmouseover="previewMouseOver(2)" onmouseleave="previewMouseLeave(2)"src={{ post.modPreviewImage2.url }} alt="Preview Image 2">
                            <p>Remove image:</p>
                            <input style="width: 20px; display: inline; margin-bottom: 10px" class="modPreviewImageCheckbox" id="modPreviewImage2-clear_id" type="checkbox" name="modPreviewImage2-clear">
                            {% endif %}
                            <input class="modPreviewImageInput" id="id_modPreviewImage2" type="file" name="modPreviewImage2" accept="image/*">

                            <input style="background-color: #8acaff; width: 100%" type="button" id="showNextButton2" onclick="showNext(3, 2)" value="Upload/change more preview images">
                        </div>
                        <div id="hiddenNextImage3">
                            <div class="previewImage">
                                {% if post.modPreviewImage3 %}
                                <div class="hidden">{{ form.modPreviewImage3 }}</div>
                                <img id="previewImage3" onmouseover="previewMouseOver(3)" onmouseleave="previewMouseLeave(3)"src={{ post.modPreviewImage3.url }} alt="Preview Image 3">
                                <p>Remove image:</p>
                                <input style="width: 20px; display: inline; margin-bottom: 10px" class="modPreviewImageCheckbox" id="modPreviewImage3-clear_id" type="checkbox" name="modPreviewImage3-clear">
                                {% endif %}
                                <input class="modPreviewImageInput" id="id_modPreviewImage3" type="file" name="modPreviewImage3" accept="image/*">
                                <input style="background-color: #8acaff; width: 100%" type="button" id="showNextButton3" onclick="showNext(4, 3)" value="Upload/change more preview images">
                            </div>
                            <div id="hiddenNextImage4">
                                <div class="previewImage">
                                    {% if post.modPreviewImage4 %}
                                    <div class="hidden">{{ form.modPreviewImage4 }}</div>
                                    <img id="previewImage4" onmouseover="previewMouseOver(4)" onmouseleave="previewMouseLeave(4)"src={{ post.modPreviewImage4.url }} alt="Preview Image 4">
                                    <p>Remove image:</p>
                                    <input style="width: 20px; display: inline; margin-bottom: 10px" class="modPreviewImageCheckbox" id="modPreviewImage4-clear_id" type="checkbox" name="modPreviewImage4-clear">
                                    {% endif %}
                                    <input class="modPreviewImageInput" id="id_modPreviewImage4" type="file" name="modPreviewImage4" accept="image/*">
                                    <input style="background-color: #8acaff; width: 100%" type="button" id="showNextButton4" onclick="showNext(5, 4)" value="Upload/change more preview images">
                                </div>
                                <div id="hiddenNextImage5">
                                    <div class="previewImage">
                                        {% if post.modPreviewImage5 %}
                                        <div class="hidden">{{ form.modPreviewImage5 }}</div>
                                        <img id="previewImage5" onmouseover="previewMouseOver(5)" onmouseleave="previewMouseLeave(5)"src={{ post.modPreviewImage5.url }} alt="Preview Image 5">
                                        <p>Remove image:</p>
                                        <input style="width: 20px; display: inline; margin-bottom: 10px" class="modPreviewImageCheckbox" id="modPreviewImage5-clear_id" type="checkbox" name="modPreviewImage5-clear">
                                        {% endif %}
                                        <input class="modPreviewImageInput" id="id_modPreviewImage5" type="file" name="modPreviewImage5" accept="image/*">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <script>
                    if ($('#id_modPreviewImage1').get(0).files.length > 0) {
                        console.log("yaes")
                    }
                    function check() {
                        if ($('#id_modPreviewImage1').get(0).files.length > 0) {
                            console.log("yaes")
                        }
                    }
                </script>
            </div>
        </div>
        <div>
            <div class="rowLeft">
                <p>Background Image: </p>
            </div>
            <div class="rowRight">
                <div class="previewImage">
                    {% if post.modBackground %}
                    <div class="hidden">{{ form.modBackground }}</div>
                    <img id="previewImage6" onmouseover="previewMouseOver(6)" onmouseleave="previewMouseLeave(6)"src={{ post.modBackground.url }} alt="Avatar image">
                    <p>Remove image:</p>
                    <input style="width: 20px; display: inline; margin-bottom: 10px" class="modPreviewImageCheckbox" id="modBackground-clear_id" type="checkbox" name="modBackground-clear">
                    {% endif %}
                    <input class="modPreviewImageInput" id="id_modBackground" type="file" name="modBackground" accept="image/*">
                    {{ form.modBackgroundTiledStretch }}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="rowLeft">
                <p>Avatar Image: </p>
            </div>
            <div class="rowRight">
                <div class="previewImage">
                    {% if post.modAvatar %}
                    <div class="hidden">{{ form.modAvatar }}</div>
                    <img src={{ post.modAvatar.url }} alt="Avatar image">
                    <p>Remove image:</p>
                    <input style="width: 20px; display: inline; margin-bottom: 10px" class="modPreviewImageCheckbox" id="modAvatar-clear_id" type="checkbox" name="modAvatar-clear">
                    {% endif %}
                    <input class="modPreviewImageInput" id="id_modAvatar" type="file" name="modAvatar" accept="image/*">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="rowLeft">
                <p>Contact Info: </p>
            </div>
            <div class="rowRight">
                {{ form.modContact }}
            </div>
        </div>
        <p style="text-align: center; color: red">Note! If your mod is NSFW, please add a "nsfw" tag in the "Tags" box above.</p>
        <div class="uploadBottom">
            <span>Don't forget to tell your followers that you have updated your mod by adding news!</span><br>
            <a href="{% url 'mod:modPage' pk=post.pk %}" style="padding-right: 50px"><p>Cancel edit</p></a>
            {% if alreadyEdited %}
                <p><input onclick="return confirm('You have already submitted an edit for this mod. If you submit another edit, all of the changes that you made in your previous edit will be lost! Make sure you have applied the changes on this page, or wait until a moderator has approved the edit.')" type="submit", value="Submit"></p>
            {% else %}
                <p><input onclick="return confirm('Are you sure you want to edit your mod? It will need to be verified by the moderators again, meaning your mod will show the old version of the mod until the edit has been approved by a moderator.')" type="submit" value="Submit"></p>
            {% endif %}
            <a onclick="return confirm('Are you sure? Once you delete the mod, it is gone forever without any way of getting it back.')" href="{% url 'mod:modDelete' pk=post.pk %}" style="padding-left: 50px"><p>Delete mod</p></a>
        </div>
    </form>
    {% else %}
    <p>Your mod is still being approved. Please check back later.</p>
    <p>If you have been waiting for longer than a week, please contact the moderators on the discord server.</p>
    {% endif %}
    {% else %}
    <p>You must be the mod creator to edit this mod.</p>
    {% endif %}
</div>
{% endblock %}

mod/templates/mod/submitted.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Submitted</title>
</head>
<body>
<h1>Submitted</h1>
</body>
</html>