accounts/urls.py
from django.urls import path, include

from . import views
from mod.views import ratingDelete

app_name = 'accounts'

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', views.profile, name='profile'),
    path('<str:pk>/profile', views.userProfile, name='userProfile'),
    path('signup/', views.SignUpView, name='signup'),
    path('account_activation_sent', views.account_activation_sent, name='account_activation_sent'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         views.activate, name='activate'),
    path('passwordReset/', views.PasswordResetForm, name='passwordReset'),
    path('passwordChange/', views.change_password, name='change_password'),
    path('profile/edit/', views.edit, name='edit'),
    path('profile/avatar', views.avatar, name='avatar'),
    path('profile/bio', views.bio, name='bio'),
    path('profile/note', views.note, name='note'),
    path('profile/ratingdelete/', ratingDelete, name='ratingDelete'),
]

api/urls.py
from django.urls import path, include
from rest_framework import routers, serializers, viewsets

from mod.models import Mod
from .views import latest, modSearch, modDownload


router = routers.DefaultRouter()

router.register(r'mod/modDownload', modDownload)
router.register(r'mod/latest', latest)
router.register(r'mod', modSearch)


urlpatterns = [
    path('', include(router.urls)),
    path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

from . import views

urlpatterns = [
    #path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('pages.urls')),
    path('mod/', include('mod.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path(r'^progressbarupload/', include('progressbarupload.urls')),
    path('avatar/', include('avatar.urls')),

]

handler404 = views.handler404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

from . import views

urlpatterns = [
    #path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('pages.urls')),
    #path('mod/', include('mod.urls')),
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    #path('accounts/', include('accounts.urls')),
    #path('avatar/', include('avatar.urls')),
    path('api/', include('api.urls')),
]

handler404 = views.handler404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, User, BaseUserManager, AbstractBaseUser, PermissionsMixin, UserManager
from django.contrib.auth import get_user_model
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.core.exceptions import ValidationError

from easy_thumbnails.fields import ThumbnailerImageField
from captcha.fields import ReCaptchaField

import string, random

# Create your models here.

def randomStringDigits():
    """Generate a random string of letters and digits """
    lettersAndDigits = string.ascii_letters + string.digits
    return ''.join(random.choice(lettersAndDigits) for i in range(50))


def avatar_path(instance, filename):
    ext = filename.split(".")[-1]
    return 'files/user_{0}/avatar/{1}.{2}'.format(instance.avatarUserID.id, randomStringDigits(), ext)


class User(AbstractUser):
    email = models.EmailField(unique=True)
    #email = VerifiedEmailField('email', fieldsetup_id='email')
    #captcha = ReCaptchaField()
    email_confirmed = models.BooleanField(default=False)
    description = models.CharField(max_length=1000, null=True)
    totalComments = models.IntegerField('total comments', default=0)
    totalMods = models.IntegerField('total mods', default=0)

    REQUIRED_FIELDS = ('username', 'password')

    USERNAME_FIELD = 'email'

    class Meta:
        app_label = 'accounts'
    pass

    def __str__(self):
        return self.username


#@receiver(post_save, sender=User)
#def update_user_profile(sender, instance, created, **kwargs):
#    if created:
#        User.objects.create(email=instance.email, )


class Avatar(models.Model):
    avatarID = models.AutoField("avatar id", primary_key=True, unique=True)
    avatarUserID = models.ForeignKey('accounts.User', on_delete=models.CASCADE, related_name="avatarUser", to_field="id", unique=True)
    avatarTime = models.DateTimeField(auto_now=True)
    avatarImage = ThumbnailerImageField('avatar image', upload_to=avatar_path, blank=True, resize_source=dict(size=(200, 200), sharpen=True, upscale=True))
    avatarApproved = models.BooleanField('avatar moderation approval', default=False)
    avatarIP = models.CharField('mod user ip address', max_length=100)


    def __str__(self):
        return str(self.avatarUserID)

    def __int__(self):
        return self.avatarID

    def clean(self):
        if self.avatarImage is None:
            raise ValidationError('Please select an image to upload for your avatar, or click back.')

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.forms import password_validation
from django.contrib.auth.forms import UsernameField
from django.contrib.auth import get_user_model

from .models import User, Avatar
from easy_thumbnails.fields import ThumbnailerImageField
from captcha.widgets import ReCaptchaV3
from captcha.fields import ReCaptchaField


class CustomUserCreationForm(UserCreationForm):
    #email = VerifiedEmailField(label='email', required=True)
    email = forms.EmailField(max_length=254, help_text='Required. Enter a valid email address.')
    #captcha = ReCaptchaField(widget=ReCaptchaV3)

    class Meta(UserCreationForm):
        model = User
        fields = ('username', 'email')#, 'captcha')


class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm):
        model = User
        fields = ('username', 'email')


class EditForm(forms.ModelForm):
    email = forms.EmailField()
    description = forms.CharField(max_length=1000)

    class Meta:
        model = User
        fields = ['email', 'description']


class AvatarForm(forms.ModelForm):
    class Meta:
        model = Avatar
        fields = ('avatarID', 'avatarImage')


#class SignUp(forms.ModelForm):
    #username = forms.CharField(max_length=100)
    #email = forms.CharField(max_length=100)
    #firstName = forms.CharField(max_length=100, required=False)
    #lastName = forms.CharField(max_length=100, required=False)
    #password1 = forms.PasswordInput()
    #password2 = forms.PasswordInput()
#    """
#    A form that creates a user, with no privileges, from the given username and
#    password.
#    """
#    error_messages = {
#        'password_mismatch': ("The two password fields didn't match."),
#    }
#    password1 = forms.CharField(
#        label=("Password"),
#        strip=False,
#        widget=forms.PasswordInput,
#        help_text=password_validation.password_validators_help_text_html(),
#    )
#    password2 = forms.CharField(
#        label=("Password confirmation"),
#        widget=forms.PasswordInput,
#        strip=False,
#        help_text=("Enter the same password as before, for verification."),
#    )

#    class Meta:
#        model = get_user_model()
#        fields = ("username",)
#        field_classes = {'username': UsernameField}

#    def __init__(self, *args, **kwargs):
#        super().__init__(*args, **kwargs)
#        if self._meta.model.USERNAME_FIELD in self.fields:
#            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs.update({'autofocus': True})

#    def clean_password2(self):
#        password1 = self.cleaned_data.get("password1")
#        password2 = self.cleaned_data.get("password2")
#        if password1 and password2 and password1 != password2:
#            raise forms.ValidationError(
#                self.error_messages['password_mismatch'],
#                code='password_mismatch',
#            )
#        return password2

#    def _post_clean(self):
#        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
#        password = self.cleaned_data.get('password2')
#        if password:
#            try:
#                password_validation.validate_password(password, self.instance)
#            except forms.ValidationError as error:
#                self.add_error('password2', error)

#    def save(self, commit=True):
#        user = super().save(commit=False)
#        user.set_password(self.cleaned_data["password1"])
#        if commit:
#            user.save()
#        return user

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm, PasswordResetForm
from django.views import generic
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse_lazy
#from django.contrib.auth.models import User
from django.views.generic.edit import CreateView
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.views import PasswordResetView
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from .tokens import AccountActivationTokenGenerator, account_activation_token
from django.contrib.auth import authenticate, login

from .forms import CustomUserCreationForm, EditForm, AvatarForm#, SignUp
from .models import Avatar, User

from mod.models import Mod
from mod.models import Rating
from mod.models import ReviewRating

import json, pdb


# Create your views here.


def visitor_ip_address(request):

    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')

    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

@login_required
def profile(request):
    try:
        userAvatar = Avatar.objects.get(avatarUserID=request.user)
    except ObjectDoesNotExist:
        userAvatar = None
        #userAvatar = Avatar.objects.create(avatarUserID=request.user, avatarImage=static('img/icon.png'))

    try:
        mods = Mod.objects.filter(modAuthor=request.user.id)
    except:
        mods = "No mods found!"

    played = Rating.objects.filter(ratingAuthorID=request.user.id)
    reviews = ReviewRating.objects.filter(reviewAuthorID=request.user.id)

    return render(request, 'accounts/profile.html', {'avatar': userAvatar, 'mods': mods, 'played': played,
                                                     'reviews': reviews})


#class SignUpView(CreateView):
#    form_class = CustomUserCreationForm
#    success_url = reverse_lazy('login')
#    template_name = 'registration/signup.html'

def SignUpView(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            subject = "Activate your dokidokimodclub.com account"
            message = render_to_string('registration/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject, message, from_email='do-not-reply@dokidokimodclub.com')
            return redirect('accounts:account_activation_sent')
    else:
        form = CustomUserCreationForm
    return render(request, 'registration/signup.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('home')
    else:
        return render(request, 'registration/account_activation_invalid.html')

class PasswordResetView(PasswordResetView):
    form_class = PasswordResetForm
    success_url = reverse_lazy('login')
    template_name = 'registration/password_reset_form.html'


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('accounts:profile')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'registration/changePassword.html', {
        'form': form
    })


def userProfile(request, pk):
    post = get_object_or_404(User, pk=User.objects.get(username=pk).id)
    try:
        userAvatar = Avatar.objects.get(avatarUserID=User.objects.get(username=pk).id)
    except ObjectDoesNotExist:
        userAvatar = None
    try:
        mods = Mod.objects.filter(modAuthor=User.objects.get(username=pk).id)
    except ObjectDoesNotExist:
        mods = "No mods found!"

    played = Rating.objects.filter(ratingAuthorID=User.objects.get(username=pk).id)
    reviews = ReviewRating.objects.filter(reviewAuthorID=User.objects.get(username=pk).id)
    return render(request, 'accounts/userProfile.html', {'post': post, 'avatar': userAvatar, 'mods': mods,
                                                         'played': played, 'reviews': reviews})


@login_required
def edit(request):
    user = request.user

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)

            user.save()
            return redirect('accounts:profile')
    else:
        form = CustomUserCreationForm()
    return render(request, "accounts/edit.html", {'form': form})


@login_required
def avatar(request):
    if request.method == 'POST':
        form = AvatarForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.avatarUserID = request.user
            post.avatarIP = visitor_ip_address(request)
            try:
                if Avatar.objects.get(avatarUserID=request.user):
                    Avatar.objects.get(avatarUserID=request.user).delete()
            except:
                pass
            post.save()
            return redirect('accounts:profile')
    else:
        form = AvatarForm()
    return render(request, 'accounts/avatar.html', {'form': form})


@login_required
def bio(request):
    if request.method == 'POST':
        newBio = request.POST.get('message')
        user = User.objects.get(id=request.user.id)
        user.description = newBio
        user.save()
        response_data = {}
        response_data['result'] = 'Successfully updated description.'

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )


@login_required
def note(request):
    if request.method == 'POST':
        newNote = request.POST.get('note')
        ratingID = request.POST.get('ratingID')
        rating = Rating.objects.get(ratingID=ratingID)
        rating.ratingNote = newNote
        rating.save()
        response_data = {}
        response_data['result'] = 'Successfully updated note.'

        return HttpResponse(
            json.dumps(response_data),
            content_type="application/json"
        )
    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )

def account_activation_sent(request):
    return render(request, 'registration/account_activation_sent.html')

accounts/templates/accounts/avatar.html
{% extends 'base.html' %}
{% block content %}
    <title>Change your avatar</title>
        <h1>Change your avatar</h1>
        <form method="post" enctype="multipart/form-data" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <p>Check out the <a href="{% url "rules" %}">rules</a> before submitting your avatar.</p>
            <p>If you want to return your avatar to the default image, leave the above slot free and click submit.</p>
            <input class="avatarSubmit" type="submit" value="Submit">
        </form>
    <p><a onclick="history.back()"><input type="button" value="Back"></a></p>
{% endblock %}

accounts/templates/accounts/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
    {% if user.is_authenticated %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.avatar }}
            <input type="submit" value="Submit">
        </form>
    {% endif %}
{% endblock %}
</body>
</html>

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}

{% block content %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <script type="text/javascript" src="{% static 'accounts/js/profile.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile.css' %}">
    <title>Your Profile</title>
    {% if user.is_authenticated %}
        <div class="userLeftSideBar">
            <div class="userLeftSideBarAvatar">
                {% if avatar.avatarImage and avatar.avatarApproved %}
                    <img src={{ avatar.avatarImage.url }}>
                {% else %}
                    <img src="{% static 'img/icon.png' %}" alt="Avatar Image">
                {% endif %}
            </div>
            <div class="userLeftSideBarData">
                {% if avatar.avatarImage and avatar.avatarApproved == False %}
                    <p>Your new avatar is being approved.</p>
                {% endif %}
                <p><a href="{% url 'accounts:avatar' %}"><input type="button" value="Edit avatar"></a></p>
                <p>Username: {{ user.username }}</p>
                <p>Email: {{ user.email }}</p>
                <p>Total comments: {{ user.totalComments }}</p>
                <p>Total mods: {{ user.totalMods }}</p>
                <p><input type="button" id="showEdit" onclick="showEdit()" value="Edit account"></p>
                <div id="userLeftSideBarEdit" class="userLeftSideBarEdit">
                    <p><a href="{% url 'accounts:change_password' %}">Change password</a></p>
                    <p>Please contact an admin to change anything else.</p>
                </div>
            <p>This is your private, editable profile. <a href="../{{ user.username }}/profile">Here</a> is your public page.</p>
            </div>
        </div>
        <div class="userRightSideContent">
            <div class="userRightSideContentBio">
                <textarea id="bio">{{ user.description }}</textarea>
                <div class="userRightSideContentBioSubmit">
                    <p id="bioUpdated">Bio updated!</p>
                    <input type="button" id="finishEditBio" value="Update bio" onclick="editBioAjax($('textarea#bio').val())">
                </div>
            </div>
            <div class="userRightSideContentCreatedMods">
                <div class="userTitle"><p>Created mods</p></div>
                <div class="createdModsTable">
                    <table>
                        <tr>
                            <th><p>Avatar</p></th>
                            <th><p>Mod name</p></th>
                            <th><p>Average rating</p></th>
                            <th><p>Status</p></th>
                            <th><p>Release date</p></th>
                        </tr>
                        {% for mods in mods %}
                            {% if mods.modShow %}
                            <tr>
                                <td>
                                    {% if mods.modAvatar %}
                                        <a href="../../mod/{{ mods.modID|stringformat:'i' }}"><img src={{ mods.modAvatar.url }} alt="Avatar Image"></a>
                                    {% else %}
                                        <a href="../../mod/{{ mods.modID|stringformat:'i' }}"><img src="{% static 'img/icon.png' %}" alt="Avatar Image"></a>
                                    {% endif %}
                                </td>
                                <td><p>{{ mods.modName }}</p></td>
                                <td><p>{{ mods.modRating }}</p></td>
                                <td><p>{{ mods.modStatus }}</p></td>
                                <td><p>{{ mods.modDate }}</p></td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="userPlayed">
            <table>
                <tr>
                    <th><p>Avatar</p></th>
                    <th><p>Mod name</p></th>
                    <th><p>Your rating</p></th>
                    <th><p>Played status</p></th>
                    <th><p>Mod note</p></th>
                    <th><p>Delete rating</p></th>
                </tr>
                {% for x in played %}
                    <tr id="rating{{ x.ratingID }}">
                        <td>
                            {% if x.ratingAvatar %}
                                <a href="../../mod/{{ x.ratingModID|stringformat:'i' }}"><img src={{ x.ratingAvatar }} alt="Avatar Image"></a>
                            {% else %}
                                <a href="../../mod/{{ x.ratingModID|stringformat:'i' }}"><img src="{% static 'img/icon.png' %}" alt="Avatar Image"></a>
                            {% endif %}</td>
                        <td><p><a href="../../mod/{{ x.ratingModID|stringformat:'i' }}">{{ x.ratingModID }}</a></p></td>
                        <td width="200px"><fieldset id="rating{{ x.ratingID }}" class="rating">
                            <input type="radio" id="{{ x.ratingID }}star5" name="rating" value="5" /><label for="star5" title="Rocks!">5 stars</label>
                            <input type="radio" id="{{ x.ratingID }}star4" name="rating" value="4" /><label for="star4" title="Pretty good">4 stars</label>
                            <input type="radio" id="{{ x.ratingID }}star3" name="rating" value="3" /><label for="star3" title="Meh">3 stars</label>
                            <input type="radio" id="{{ x.ratingID }}star2" name="rating" value="2" /><label for="star2" title="Kinda bad">2 stars</label>
                            <input type="radio" id="{{ x.ratingID }}star1" name="rating" value="1" /><label for="star1" title="Sucks big time">1 star</label>
                        </fieldset>
                        <script>
                            if (document.getElementById("rating{{ x.ratingID }}").hasAttribute("hidden")) {
                                document.getElementById("star{{ x.ratingValue }}").checked = true;
                            }
                            if ('{{ x.ratingValue }}' != 'None') {
                                document.getElementById("{{ x.ratingID }}star{{ x.ratingValue }}").checked = true;
                            }
                        </script></td>
                        <td><p>{{ x.ratingChoice }}</p></td>
                        <td><textarea placeholder="Click out of the box to update this" id="editNote{{ x.ratingID }}" onfocusout="editNoteAjax($('#editNote{{ x.ratingID }}').val(), {{ x.ratingID }})">{{ x.ratingNote }}</textarea></td>
                        {% if user == x.ratingAuthorID %}
                            <td id="rating{{ x.ratingID }}Delete"><p></p><input type="button" id="rating{{ x.ratingID }}DeleteButton" value="Delete" onclick="confirmDeleteRating({{ x.ratingID }})"><input type="button" id="rating{{ x.ratingID }}DeleteYes" class="hidden" value="Yes" onclick="deleteRatingButton({{ x.ratingID }})"><input type="button" id="rating{{ x.ratingID }}DeleteNo" class="hidden" value="No" onclick="revertDeleteRating({{ x.ratingID }})"></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% else %}
        <p>You are not logged in.</p>
        <p><a href="{% url 'login' %}">Login</a></p>
    {% endif %}
{% endblock %}

<!--JAVASCRIPT-->

accounts/templates/accounts/userProfile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static %}


{% block content %}
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/css/profile.css' %}">
    <title>{{ post.username }}'s Profile</title>
    {% if user.is_authenticated %}
        <div class="userLeftSideBar">
            <div class="userLeftSideBarAvatar">
                {% if avatar.avatarImage %}
                    <img src={{ avatar.avatarImage.url }}>
                {% else %}
                    <img src="{% static 'img/icon.png' %}" alt="Avatar Image">
                {% endif %}
            </div>
            <div class="userLeftSideBarData">
                <p>Username: {{ post.username }}</p>
                <p>Total comments: {{ post.totalComments }}</p>
                <p>Total mods: {{ post.totalMods }}</p>
            </div>
        </div>
        <div class="userRightSideContent">
            <div class="userRightSideContentBio">
                <p style="text-align: left; margin: 5px 5px" id="bio">{{ post.description|linebreaks }}</p>
            </div>
            <div class="userRightSideContentCreatedMods">
                <div class="userTitle"><p>Created mods</p></div>
                <div class="createdModsTable">
                    <table>
                        <tr>
                            <th><p>Avatar</p></th>
                            <th><p>Mod name</p></th>
                            <th><p>Average rating</p></th>
                            <th><p>Status</p></th>
                            <th><p>Release date</p></th>
                        </tr>
                        {% for mods in mods %}
                            <tr>
                                <td>
                                    {% if mods.modAvatar %}
                                        <a href="../../mod/{{ mods.modID|stringformat:'i' }}"><img src={{ mods.modAvatar.url }} alt="Avatar Image"></a>
                                    {% else %}
                                        <a href="../../mod/{{ mods.modID|stringformat:'i' }}"><img src="{% static 'img/icon.png' %}" alt="Avatar Image"></a>
                                    {% endif %}
                                </td>
                                <td><p><a href="../../mod/{{ mods.modID|stringformat:'i' }}">{{ mods.modName }}</a></p></td>
                                <td><p>{{ mods.modRating }}</p></td>
                                <td><p>{{ mods.modStatus }}</p></td>
                                <td><p>{{ mods.modDate }}</p></td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
        <div class="userPlayed">
            <table>
                <tr>
                    <th><p>Avatar</p></th>
                    <th><p>Mod name</p></th>
                    <th><p>Your rating</p></th>
                    <th><p>Played status</p></th>
                    <th><p>Mod note</p></th>
                </tr>
                {% for x in played %}
                    <tr id="rating{{ x.ratingID }}">
                        <td>
                            {% if x.ratingAvatar %}
                                <a href="../../mod/{{ x.ratingModID|stringformat:'i' }}"><img src={{ x.ratingAvatar }} alt="Avatar Image"></a>
                            {% else %}
                                <a href="../../mod/{{ x.ratingModID|stringformat:'i' }}"><img src="{% static 'img/icon.png' %}" alt="Avatar Image"></a>
                            {% endif %}
                        </td>
                        <td><p><a href="../../mod/{{ x.ratingModID|stringformat:'i' }}">{{ x.ratingModID }}</a></p></td>
                        <td width="200px"><fieldset id="rating{{ x.ratingID }}" class="rating">
                            <input type="radio" id="{{ x.ratingID }}star5" name="rating" value="5" /><label for="star5" title="Rocks!">5 stars</label>
                            <input type="radio" id="{{ x.ratingID }}star4" name="rating" value="4" /><label for="star4" title="Pretty good">4 stars</label>
                            <input type="radio" id="{{ x.ratingID }}star3" name="rating" value="3" /><label for="star3" title="Meh">3 stars</label>
                            <input type="radio" id="{{ x.ratingID }}star2" name="rating" value="2" /><label for="star2" title="Kinda bad">2 stars</label>
                            <input type="radio" id="{{ x.ratingID }}star1" name="rating" value="1" /><label for="star1" title="Sucks big time">1 star</label>
                        </fieldset>
                            <script>
                                if (document.getElementById("rating{{ x.ratingID }}").hasAttribute("hidden")) {
                                    document.getElementById("star{{ x.ratingValue }}").checked = true;
                                }
                                if ('{{ x.ratingValue }}' != 'None') {
                                    document.getElementById("{{ x.ratingID }}star{{ x.ratingValue }}").checked = true;
                                }
                            </script></td>
                        <td><p>{{ x.ratingChoice }}</p></td>
                        <td width="150px"><p>{{ x.ratingNote }}</p></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    {% else %}
        <p>You are not logged in.</p>
        <p><a href="{% url 'login' %}">Login</a></p>
    {% endif %}
{% endblock %}

<!--JAVASCRIPT-->