accounts/urls.py
from django.urls import path, include

from . import views
from mod.views import ratingDelete

app_name = 'accounts'

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', views.profile, name='profile'),
    path('<str:pk>/profile', views.userProfile, name='userProfile'),
    path('signup/', views.SignUpView, name='signup'),
    path('account_activation_sent', views.account_activation_sent, name='account_activation_sent'),
    path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
         views.activate, name='activate'),
    path('passwordReset/', views.PasswordResetForm, name='passwordReset'),
    path('passwordChange/', views.change_password, name='change_password'),
    path('profile/edit/', views.edit, name='edit'),
    path('profile/avatar', views.avatar, name='avatar'),
    path('profile/bio', views.bio, name='bio'),
    path('profile/note', views.note, name='note'),
    path('profile/ratingdelete/', ratingDelete, name='ratingDelete'),
]

api/urls.py
from django.urls import path, include
from rest_framework import routers, serializers, viewsets

from mod.models import Mod
from .views import latest, modSearch, modDownload


router = routers.DefaultRouter()

router.register(r'mod/modDownload', modDownload)
router.register(r'mod/latest', latest)
router.register(r'mod', modSearch)


urlpatterns = [
    path('', include(router.urls)),
    path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

from . import views

urlpatterns = [
    #path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('pages.urls')),
    path('mod/', include('mod.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path(r'^progressbarupload/', include('progressbarupload.urls')),
    path('avatar/', include('avatar.urls')),

]

handler404 = views.handler404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler404

from . import views

urlpatterns = [
    #path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('', include('pages.urls')),
    #path('mod/', include('mod.urls')),
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    #path('accounts/', include('accounts.urls')),
    #path('avatar/', include('avatar.urls')),
    path('api/', include('api.urls')),
]

handler404 = views.handler404

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/templates/pages/DMCA.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <title>Copyright claims</title>
    <h1>Copyright claims</h1>
    <p>If you believe someone has copied your creations without your permission, please <a href="{% url 'contactUs' %}">contact us</a> so we can sort the problem out. If any problems are found, the mod and all of the data of the mod will be removed from the server so it will no longer be available.</p>
{% endblock %}

pages/templates/pages/claim.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'pages/css/supportHome.css' %}">

<title>Claiming a mod as your own work</title>
<h1>Claiming a mod as your own work</h1>
<p>Have you found a mod that does not have an owner? If you claim the mod as your own, you can edit it freely!</p>
<p>You will have to verify that you have made the mod, and so to do this you must show that you are the original poster of the mod on the sub-reddit.</p>
    <p>To do this, you can contact me via <a href="https://discordapp.com/users/105625086739931136">discord</a> or DM me on <a href="https://www.reddit.com/user/wayylmao">reddit</a>. Contacting me via reddit would be much more helpful because I will be able to see your post history.</p>
<p>If neither of these methods work, go to the support page and join our discord. Someone there will be able to help you.</p>

{% endblock %}

pages/templates/pages/contactUs.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <title>Contact Us</title>
    <h1>Contact Us</h1>
    <p>Email - you can contact us via email at dokidokimodclub@protonmail.com</p>
    <p>Discord - fastest and probably easiest way to contact us, join the discord server and we can answer your questions quickly.</p>
    <iframe src="https://discordapp.com/widget?id=625672295435862047&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0"></iframe>
    <p>Discord direct message - you can also contact the head admin through direct message on discord with <a href="https://discordapp.com/users/105625086739931136">this link.</a></p>
{% endblock %}

pages/templates/pages/developer.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <title>Developers</title>
    <p>We currently support an API for developers that want to access the websites database of mods. You can see the documentation for it <a href="https://app.swaggerhub.com/apis-docs/doki-doki-mod-club/doki-doki-mod-club/1.0.0">here</a>.</p>
    <p>You will need to <a href="{% url 'contactUs' %}">contact</a> the head admin to get an API key to access the database. This is to stop abuse of the feature.</p>
    <p>If you would like access to more data that is available on the website, please ask for it to be implemented.</p>
{% endblock %}

pages/templates/pages/myAccountSupport.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Deleting account</h1>
    <p>If you would like to delete your account, <a href="{% url 'contactUs' %}">contact us</a> and we will remove all data that is associated with your account from our system. This includes mods, comments and any other submitted data.</p>
    <h1><a name="edit"></a>Editing account</h1>
    <p>You can personalize your account by adding an avatar and a description. You can edit these by navigating to your <a href="{% url 'accounts:profile' %}">profile</a>. Please note that there is a <b>1000 character limit</b> to your description, and your avatar will be scaled to 200x200.</p>
    <p>You can also change your password on your profile page. Any other data cannot be changed unfortunately, and you will have to <a href="{% url 'contactUs' %}">contact us</a> to change any other data.</p>
{% endblock %}

pages/templates/pages/news.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'pages/css/pages.css' %}">
    <title>News</title>
    <h1>News</h1>
    <p>Every major update to the website is announced here, on the news page. Minor updates are only announced on the <a href="{% url 'contactUs' %}">discord server</a>.</p>
    <div class="adminNews">
        <ul class="news">
            {% for news in adminNews %}
                <li class="adminNewsContent">
                    <div class="newsUserBar">
                        <p class="newsUser">{{ news.adminNewsUserID }}</p>
                        <p class="newsDate">{{ news.adminNewsDate }}</p>
                    </div>
                    <div class="newsContent">
                        <p>{{ news.adminNewsText|linebreaks }}</p>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

pages/templates/pages/otherUsersModsSupport.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <script type="text/javascript" src="{% static 'pages/js/support.js' %}"></script>
    <title>Other Users and their Mods | Support</title>
    <h1>Reporting misconduct</h1>
    <p>If you would like to report others users and/or their mods, as you have found something that is against the <a href="">rules</a> of the website, you can <a href="{% url 'contactUs' %}">contact us</a>. If you believe it to be an emergency, please contact the admin through private discord chat.</p>
    <h1><a name="reviews"></a>Reporting reviews</h1>
    <p>If you have found a review that does not respect the <a href="{% url 'rules' %}">rules</a>, please <a href="{% url 'contactUs' %}">contact us</a> and we will fix the problem.</p>
{% endblock %}

pages/templates/pages/privacypolicy.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Terms of use</h1>
    <p>This website is intended to promote users mods created for the game, Doki Doki Literature Club. This website does not host the original game, only the modification files for the game. Any content that is deemed illegal will be held by the moderators, and the IP of the user that submitted the content will be banned, and if necessary, the local authorities will be notified. </p>
    <h1>Privacy Policy</h1>
    <p>This privacy notice discloses the privacy practices for dokidokimodclub.com. This privacy notice applies solely to information collected by this website. It will notify you of the following:</p>
    <ol>
        <li><p>What personally identifiable information is collected from you through the website, how it is used and with whom it may be shared.</p></li>
        <li><p>What choices are available to you regarding the use of your data.</p></li>
        <li><p>The security procedures in place to protect the misuse of your information.</p></li>
        <li><p>How you can correct any inaccuracies in the information.</p></li>
    </ol>
    <p><b>Information Collection, Use, and Sharing</b></p>
    <p>We are the sole owners of the information collected on this site. We only have access to/collect information that you voluntarily give us via email or other direct contact from you. We will not sell or rent this information to anyone.</p>
    <p>We will use your information to respond to you, regarding the reason you contacted us. We will not share your information with any third party outside of our organization, other than as necessary to fulfill your request.</p>
    <p>Unless you ask us not to, we may contact you via email in the future to tell you about specials, new products or services, or changes to this privacy policy.</p>
    <p>In order to use this website, a user must first complete the registration form. During registration a user is required to give certain information (such as name and email address). This information is used to contact you about the products/services on our site in which you have expressed interest.</p>
    <p>We use "cookies" on this site. A cookie is a piece of data stored on a site visitor's hard drive to help us improve your access to our site and identify repeat visitors to our site. For instance, when we use a cookie to identify you, you would not have to log in a password more than once, thereby saving time while on our site. Cookies can also enable us to track and target the interests of our users to enhance the experience on our site. Usage of a cookie is in no way linked to any personally identifiable information on our site.</p>
    <p>Some of our business partners may use cookies on our site (for example, advertisers). However, we have no access to or control over these cookies.</p>
    <p>We share aggregated demographic information with our partners and advertisers. This is not linked to any personal information that can identify any individual person.</p>
    <p>This website contains links to other sites. Please be aware that we are not responsible for the content or privacy practices of such other sites. We encourage our users to be aware when they leave our site and to read the privacy statements of any other site that collects personally identifiable information.</p>
    <p>From time-to-time our site requests information via surveys or contests. Participation in these surveys or contests is completely voluntary and you may choose whether or not to participate and therefore disclose this information. Information requested may include contact information (such as name and email address). Contact information will be used to notify the winners and award prizes. Survey information will be used for purposes of monitoring or improving the use and satisfaction of this site.</p>
    <p><b>Your Access to and Control Over Information</b></p>
    <p>You may opt out of any future contacts from us at any time. You can do the following at any time by contacting us via the email address given on our website:</p>
    <ol>
        <li><p>See what data we have about you, if any.</p></li>
        <li><p>Change/correct any data we have about you.</p></li>
        <li><p>Have us delete any data we have about you.</p></li>
        <li><p>Express any concern you have about our use of your data.</p></li>
    </ol>
    <p><b>Security</b></p>
    <p>We take precautions to protect your information. When you submit sensitive information via the website, your information is protected both online and offline.</p>
    <p>Wherever we collect sensitive information (such as credit card data), that information is encrypted and transmitted to us in a secure way. You can verify this by looking for a lock icon in the address bar and looking for "https" at the beginning of the address of the Web page.</p>
    <p>While we use encryption to protect sensitive information transmitted online, we also protect your information offline. Only employees who need the information to perform a specific job (for example, billing or customer service) are granted access to personally identifiable information. The computers/servers in which we store personally identifiable information are kept in a secure environment.</p>
    <p><b>If you feel that we are not abiding by this privacy policy, you should contact us immediately via email.</b></p>
{% endblock %}

pages/templates/pages/rules.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'pages/css/supportHome.css' %}">
    <title>Rules and TOS</title>
    <h1>Rules and TOS</h1>
    <ol>
        <li><p>Do not upload anything onto this website that would be deemed illegal. Misuse of uploading services will be dealt with harshly, if necessary authorities will be contacted.</p></li>
        <li><p>If necessary, any data held by us will be handed over to the authorities if the need arises.</p></li>
        <li><p>No pornographic content is allowed.</p></li>
        <li><p>Target criticism at the mod, not the creator.</p></li>
        <li><p>Advertising your YouTube/twitch/reddit whatever is allowed, but please do it tastefully. Don't spam it all over the place.</p></li>
        <li><p>Use common sense. If you don't think you should post/upload something, don't.</p></li>
        <li><p>Only use this website for the intended uses, which is to share mods for Doki Doki Literature Club.</p></li>
        <li><p>Only upload content that you own, or are allowed to share. Any content that is not yours will be removed, and your account may be banned from uploading any more content. You are also held responsible for the uploaded content, not the website.</p></li>
    </ol>
{% endblock %}

pages/templates/pages/supportHome.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'pages/css/supportHome.css' %}">
    <script type="text/javascript" src="{% static 'pages/js/support.js' %}"></script>
    <title>Support</title>
    <div class="supportContent">
        <h1>Support</h1>
        <p>What do you need help with?</p>
        <ul>
            <li class="supportList">
                <p onclick="showSupportListDropDown('submittingModsDropDown')">Submitting/Editing Mods</p>
                <div id="submittingModsDropDown" class="supportListDropDown">
                    <p><a href="{% url 'submittingMods' %}">How to submit a mod</a></p>
                    <p><a href="{% url 'submittingMods' %}#editmod">How to edit a mod</a></p>
                    <p><a href="{% url 'submittingMods' %}#commonerrors">Common errors</a></p>
                </div>
            </li>
            <li class="supportList">
                <p onclick="showSupportListDropDown('otherUsersModsDropDown')">Other Users and their Mods</p>
                <div id="otherUsersModsDropDown" class="supportListDropDown">
                    <p><a href="{% url 'otherUsersMods' %}">Reporting misconduct</a></p>
                    <p><a href="{% url 'otherUsersMods' %}#reviews">Reporting reviews</a></p>
                    <p><a href="{% url 'claim' %}">Claiming a mod as your own work</a></p>
                </div>
            </li>
            <li class="supportList">
                <p onclick="showSupportListDropDown('myAccountDropDown')">My Account</p>
                <div id="myAccountDropDown" class="supportListDropDown">
                    <p><a href="{% url 'myAccountSupport' %}">Deleting account</a></p>
                    <p><a href="{% url 'myAccountSupport' %}#edit">Editing account</a></p>
                </div>
            </li>
            <li class="supportList">
                <p onclick="showSupportListDropDown('helpingDropDown')">Helping me!</p>
                <div id="helpingDropDown" class="supportListDropDown">
                    <p>If you have any suggestions for the website, please go onto our discord and throw your idea into the chat. All help is much appreciated, and any really big ideas that I believe are worth it will be rewarded.</p>
                </div>
            </li>
            <li class="supportList">
                <p onclick="showSupportListDropDown('bugDropDown')">I found a bug!</p>
                <div id="bugDropDown" class="supportListDropDown">
                    <p>This is my first website, so there are sure to be some bugs found around this website. Please <a href="">contact me on discord</a> with extensive details about the bug. Thank you!</p>
                </div>
            </li>
        </ul>
    </div>
    <div class="supportDiscord">
        <p>Need support immediately? Contact us through Discord: </p>
        <iframe src="https://discordapp.com/widget?id=625672295435862047&theme=dark" width="350" height="500" allowtransparency="true" frameborder="0"></iframe>
    </div>
{% endblock %}